style(git): apply shellcheck and shfmt to git-clone-bare

diff --git a/src/tag-git/local/bin/git-clone-bare b/src/tag-git/local/bin/git-clone-bare
--- a/src/tag-git/local/bin/git-clone-bare
+++ b/src/tag-git/local/bin/git-clone-bare
@@ -5,7 +5,7 @@ set -Eeuo pipefail
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 usage() {
-  cat <<EOF
+	cat <<EOF
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] <repository> [directory]
 
 Clone a bare git repo and set up environment for working comfortably and exclusively from worktrees.
@@ -16,59 +16,59 @@ Available options:
 -v, --verbose   Print script debug info
 --no-color      Set NO_COLOR=1
 EOF
-  exit
+	exit
 }
 
 cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
+	trap - SIGINT SIGTERM ERR EXIT
 }
 
 setup_colors() {
-  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    NOFORMAT='\033[0m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
-  else
-    NOFORMAT='' GREEN='' YELLOW=''
-  fi
+	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+		NOFORMAT='\033[0m' GREEN='\033[0;32m' YELLOW='\033[1;33m'
+	else
+		NOFORMAT='' GREEN='' YELLOW=''
+	fi
 }
 
 msg() {
-  echo >&2 -e "${1-}"
+	echo >&2 -e "${1-}"
 }
 
 die() {
-  local msg=$1
-  local code=${2-1} # default exit status 1
-  msg "$msg"
-  exit "$code"
+	local msg=$1
+	local code=${2-1} # default exit status 1
+	msg "$msg"
+	exit "$code"
 }
 
 parse_location() {
-  if [[ ${#args[@]} -eq 2 ]]; then
-      location="${args[1]}"
-  else
-      location=$(echo "${args[0]}" | sed -E 's/(^[^/]+\/)|(.git$)//g')"/.git"
-  fi
+	if [[ ${#args[@]} -eq 2 ]]; then
+		location="${args[1]}"
+	else
+		location=$(echo "${args[0]}" | sed -E 's/(^[^/]+\/)|(.git$)//g')"/.git"
+	fi
 }
 
 parse_params() {
-  while :; do
-    case "${1-}" in
-    -h | --help) usage ;;
-    -v | --verbose) set -x ;;
-    --no-color) NO_COLOR=1 ;;
-    -?*) die "Unknown option: $1" ;;
-    *) break ;;
-    esac
-    shift
-  done
+	while :; do
+		case "${1-}" in
+			-h | --help) usage ;;
+			-v | --verbose) set -x ;;
+			--no-color) NO_COLOR=1 ;;
+			-?*) die "Unknown option: $1" ;;
+			*) break ;;
+		esac
+		shift
+	done
 
-  args=("$@")
+	args=("$@")
 
-  # check required params and arguments
-  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
-  parse_location
+	# check required params and arguments
+	[[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+	parse_location
 
-  return 0
+	return 0
 }
 
 parse_params "$@"
@@ -76,10 +76,10 @@ setup_colors
 
 msg "${YELLOW}Cloning bare repository to $location...${NOFORMAT}"
 git clone --bare "${args[0]}" "$location"
-pushd "$location" > /dev/null
+pushd "$location" >/dev/null
 msg "${YELLOW}Adjusting origin fetch locations...${NOFORMAT}"
 git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-popd > /dev/null
+popd >/dev/null
 msg "${YELLOW}Setting .git file contents...${NOFORMAT}"
-echo "gitdir: ./$location" > .git
+echo "gitdir: ./$location" >.git
 msg "${GREEN}Success.${NOFORMAT}"
